name: Daily Facebook Post

on:
  workflow_dispatch: # Allows you to run it manually
  schedule:
    - cron: '30 10 * * *' # Runs at 4:00 PM IST (10:30 UTC)

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow firebase-admin

      # Indentation for this step is now corrected
      - name: Run the script
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
        run: python main_script.py
